MrTweety Analytic
=================

image:https://travis-ci.org/kubahorak/mrtweety-analytic.svg?branch=master["Build Status", link="https://travis-ci.org/kubahorak/mrtweety-analytic"]

Analyses tweets in realtime to figure out the most popular hashtags.

Uses https://spark.apache.org[Apache Spark] and a https://github.com/twitter/hbc[Twitter Hosebird Client] to
retrieve top 5 tweets in a sliding window of 5 minutes. This result is stored in a JSON file and a small JS app is
producing a small website of this data.

Standalone Spark app
--------------------

To build the Spark jar, use:

    ./gradlew shadowJar

Optionally you can change the default path of the result JSON file by setting the environment variable
`RESULT_FILENAME`.

    export RESULT_FILENAME=/tmp/analytic.json

Finally submit the "fat jar" to your Spark for execution:

    spark-submit --class "cz.zee.mrtweety.analytic.spark.Application" --master 'local[4]' build/libs/spark-all.jar 

Docker
------

The Spark app together with a website showing the data and Nginx are packaged together using Docker. Just run:

    docker build -t mrtweety-analytic .


Kafka producer
--------------

Module takes tweets from the Twitter Streaming API and publishes them to the Kafka messaging system.

Start Zookeeper:

    bin/zookeeper-server-start.sh config/zookeeper.properties

Start Kafka:

    bin/kafka-server-start.sh config/server.properties

Console output of messages passing through Kafka:

    bin/kafka-console-consumer.sh --zookeeper localhost:2181 --topic tweet

Test console producer of Kafka messages:

    bin/kafka-console-producer.sh --broker-list localhost:9092 --topic tweet


(c) 2016 Jakub Horák
